### ISSUE TITLE
bug: bors doesn't handle unset commit statuses

### ISSUE THREAD

**Issue by irfansharif** [bors-ng/bors-ng#1001]
[Here's](https://github.com/cockroachdb/cockroach/blob/master/.github/bors.toml#L3-L19) the bors config we use over at https://github.com/cockroachdb/cockroach:

```toml
# List of commit statuses that must pass on the merge commit before it is
# pushed to master.
status = ["Compile Build (Cockroach)"]

# List of commit statuses that must not be failing on the PR commit when it is
# r+-ed. If it's still in progress (for e.g. if CI is still running), bors will
# construct the merge commit in parallel and simply wait for success right
# before merging.
pr_status = ["license/cla", "GitHub CI (Cockroach)"]
```

We observe this bug in bors that I think is due to racey conditions around its reliance on webhooks. If you look at https://bors.crdb.io/repositories/56/log, you'll sometimes find the following:
<img width="958" alt="image" src="https://user-images.githubusercontent.com/10536690/90089740-25a42e80-dcf0-11ea-8495-34cbab6ee46c.png">

The `bors r+` attempt in question there is https://github.com/cockroachdb/cockroach/pull/50446#issuecomment-673098315. If you look right above, the author amended their commit here https://github.com/cockroachdb/cockroach/pull/50446#event-3649360208 at Aug 12, 2020, 4:37 PM EDT. The author also almost instantly `bors r+`-ed their PR at Aug 12, 2020, 4:37 PM EDT. What I would expect to happen is that bors would wait for the "GitHub CI (Cockroach)" check on the amended commit to have run. What I think happened instead is that bors looked at the commit status for the commit before it was amended, and having seen that pass the CI check successfully, then went ahead and started the merge commit process. Unfortunately that's not behavior we want, I think what happens is that the as the merge commit checks complete and come back to find that the pr status has now failed (due to the amended commit), and thus crashing bors. This also has the unfortunate side effect of silently dropping the queue built up behind the PR in question, and all the other others who have `bors r+`-ed their PRs will not see any activity. That's what we see happen with this `bors r+` attempt: https://github.com/cockroachdb/cockroach/pull/52596#issuecomment-672021571.
