### ISSUE TITLE
Matching regexp in status

### ISSUE THREAD

**Issue by curquiza** [bors-ng/bors-ng#1061]
Hello, 

I use Bors and the GitHub actions. I have a GHA file that runs 3 similar tests (for different versions of PHP) with `matrix`:

```yml
name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - master

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test

    steps:
    - uses: actions/checkout@v1

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    ...
```

It means I launch 3 tests: `PHP 7.2 Test` `PHP 7.3 Test` and `PHP 7.4 Test`.
I wanted to use the pattern matching of the `status` field to match every `PHP ... Test`.

I tested:
- `status = ["PHP % Test"]`
- `status = ["PHP _._ Test"]`

But none worked.
Bors still returns the success of one test only. See my PR: https://github.com/meilisearch/meilisearch-php/pull/109.

Is it normal?
Sorry if it's obvious, I'm trying to learn the `LIKE` syntax with [this link](https://www.postgresql.org/docs/9.5/functions-matching.html).

Thanks!
