### ISSUE TITLE
Outgoing webhooks

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#179]
To hook into third-party, potentially project-specific services ([treeherder], for example), bors needs to be able to send webhooks to project-configured URLs.

[treeherder]: https://github.com/mozilla/treeherder

# Design

To some extent, the "right way" to do this depends on how #178 is solved. I'm going to be writing out examples in TOML format, but the final design might be done in menus instead. Anyway:

The intended design for webhooks should allow bors to do the maximum amount of heavy-lifting, allowing the project's part to just be a one-page Python script on a free Heroku node or something, but include enough information for the script to go further if it wants. A good initial design looks like the way GitHub does it, with some coarse-grained choice of event types to subscribe to, and a shared secret to validate the messages.

Also, it seems like a good idea to allow gating on them. Maybe it's not necessary to build this functionality in, though, since a developer could use the provided "token" to push their own commit statuses to GitHub directly? The real reason to have that token is so that the webhook can check out a copy of the repository...

## Configuration

```toml
[[webhooks]]
url = "https://my-kool-project-metriks.herokuapp.com/"
events = [ "started", "finished" ]
secret = "SOME_ENCRYPTED_STRING?"
# If set to true, then an Integration token (allowing the webhook to act on bors's behalf) is sent in the webhook
# Note: because of the way GitHub integration tokens work, this does not give the webhook permission to operate on any bors-managed repository. For more info on that, see https://developer.github.com/early-access/integrations/authentication/
send-github-token = true
# If set to true, and if the "started" webhook is enabled, then the integration must POST to a bors-provided URL for the build to complete.
# Otherwise, it doesn't matter.
reply = true
```

## Event type ideas

* added: A new batch is added to the queue
* dropped: A batch, still in the queue, is removed without running
* edited: Patch(es) are added / removed from a batch
* started: A batch has started building
* finished: A batch has finished building (potentially a success, an error, canceled, timeout)

### added / dropped

```json
{
    "action": "added", # or "dropped"
    "token": "Iv1.XXXXXXXX",
    "batch": "AC-79-5A-23",
    "repository": { "name": "bors-ng/bors-ng", "id": "33-9A-2C-88" },
    "patches": [ { "number": 175, "id": "22-1F-EA-95", "reviewer": "notriddle" } ]
}
```

### edited

```json
{
    "action": "edited",
    "token": "Iv1.XXXXXXXX",
    "batch": "AC-79-5A-23",
    "repository": { "name": "bors-ng/bors-ng", "id": "33-9A-2C-88" },
    "patches": [ { "number": 175, "id": "22-1F-EA-95", "reviewer": "notriddle" }, { "number": 172, "id": "58-14-CD-AA-91", "reviewer": "notriddle" } ],
    "old_patches": [ { "number": 175, "id": "22-1F-EA-95", "reviewer": "notriddle" } ]
}
```

### started

```json
{
    "action": "started",
    "token": "Iv1.XXXXXXXX",
    "batch": "AC-79-5A-23",
    "commit": "e02ef54ba3cb42bf7c82e3737349d3ed523cd971",
    "repository": { "name": "bors-ng/bors-ng", "id": "33-9A-2C-88" },
    "patches": [ { "number": 175, "id": "22-1F-EA-95", "reviewer": "notriddle" }, { "number": 172, "id": "58-14-CD-AA-91", "reviewer": "notriddle" } ],
    "builds": [
        { "name": "continuous-integration/travis-ci/push" }
    ],
    "reply_url": "https://api.bors.io/webhook/reply/AF-2C-96-38-1D" # not there if reply is unspecified, or false
}
```

### reply

```json
{ "state": "success", "url": null }
```

### finished

```json
{
    "action": "finished",
    "token": "Iv1.XXXXXXXX",
    "state": "error",
    "batch": "AC-79-5A-23",
    "commit": "e02ef54ba3cb42bf7c82e3737349d3ed523cd971",
    "repository": { "name": "bors-ng/bors-ng", "id": "33-9A-2C-88" },
    "patches": [ { "number": 175, "id": "22-1F-EA-95", "reviewer": "notriddle" }, { "number": 172, "id": "58-14-CD-AA-91", "reviewer": "notriddle" } ],
    "builds": [
        { "name": "continuous-integration/travis-ci/push" }
    ]
}
```
