### ISSUE TITLE
Automatically add/remove tags in response to events

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#288]
Basically, Rust's current policy could be duplicated with this `bors.toml` file and the code to make it work.

```toml
status = [ "continuous-integration/travis-ci/push", "continuous-integration/appveyor/branch" ]
# ... bla bla bla ...
[on.open]
remove-tags = [ "S-waiting-on-review" ]
[on.synchronize]
remove-tags = [ "S-waiting-on-author", "S-waiting-on-bors" ]
add-tags = [ "S-waiting-on-review" ]
[on.close]
remove-tags = [ "S-waiting-on-author", "S-waiting-on-review", "S-waiting-on-bors" ]
[on.review]
remove-tags = [ "S-waiting-on-review" ]
add-tags = [ "S-waiting-on-bors" ]
[on.succeed]
remove-tags = [ "S-waiting-on-bors" ]
[on.fail]
remove-tags = [ "S-waiting-on-bors" ]
add-tags = [ "S-waiting-on-author" ]
```

**Comment by behnam** [comment]
The reasons I love to see this becoming a reality:

* When bors is in work, there's no way to see that in the GH PR list page. This suggestion allows developers to address that. Even better, there could be some default values, similar to those suggestion here.

* Out-of-date labels always take a toll in communication and workflow. This is a more generic problem in GH repos, because of lack of any structure for labels. But at least we can solve it in bors-backed projects this way.

**Comment by kennytm** [comment]
FYI we have implemented automatic relabeling in homu, and deployed to Rust with the following rules (rust-lang/rust-central-station#32):

<details>

```toml
# Automatic relabeling
[repo.rust.labels.approved]   # after homu received `r+`
remove = ['S-blocked', 'S-waiting-on-author', 'S-waiting-on-bors', 'S-waiting-on-crater', 'S-waiting-on-review', 'S-waiting-on-team']
add = ['S-waiting-on-bors']

[repo.rust.labels.rejected]   # after homu received `r-`
remove = ['S-blocked', 'S-waiting-on-author', 'S-waiting-on-bors', 'S-waiting-on-crater', 'S-waiting-on-review', 'S-waiting-on-team']
add = ['S-waiting-on-author']

[repo.rust.labels.failed]     # test failed (maybe spurious, so fall back to -on-review)
remove = ['S-blocked', 'S-waiting-on-author', 'S-waiting-on-bors', 'S-waiting-on-crater', 'S-waiting-on-review', 'S-waiting-on-team']
add = ['S-waiting-on-review']

[repo.rust.labels.timed_out]   # test timed out after 4 hours (almost always spurious, let reviewer retry)
remove = ['S-blocked', 'S-waiting-on-author', 'S-waiting-on-bors', 'S-waiting-on-crater', 'S-waiting-on-review', 'S-waiting-on-team']
add = ['S-waiting-on-review']

[repo.rust.labels.try_failed]  # try-build failed (almost always legit, tell author to fix the PR)
remove = ['S-waiting-on-review', 'S-waiting-on-crater']
add = ['S-waiting-on-author']

[repo.rust.labels.pushed]      # user pushed a commit after `r+`/`try`
remove = ['S-waiting-on-bors', 'S-waiting-on-author']
add = ['S-waiting-on-review']
unless = ['S-blocked', 'S-waiting-on-crater', 'S-waiting-on-team']

[repo.rust.labels.conflict]    # a merge conflict is detected (tell author to rebase)
remove = ['S-waiting-on-bors', 'S-waiting-on-review']
add = ['S-waiting-on-author']
unless = ['S-blocked', 'S-waiting-on-crater', 'S-waiting-on-team']
```

</details>



One particular addition is the `unless` field, which prevents bors from relabeling when present.
