### ISSUE TITLE
Merges are tested twice on CI

### ISSUE THREAD

**Issue by ehuss** [bors-ng/bors-ng#441]
I'm perhaps a little confused, I couldn't find another issue related to this.

If Travis is configured to test `master` so that it automatically tests new PRs, when you approve the PR, it gets tested twice with the exact same git hash (once on staging and once when it merges to master).   Do I have it misconfigured, or is there a better way to automatically test new PRs?

**Comment by notriddle** [comment]
That's how it is, yeah. It's a limitation in what Travis supports; I don't know how to avoid it.

**Comment by ehuss** [comment]
I was experimenting with something like:

```yml
branches:
  only:
    - staging
    - trying
    - master

matrix:
  include:
    - name: "Bors"
      if: branch = staging OR branch = trying
    - name: "PR Open"
      if: type = pull_request AND branch = master
```

It seems to work, I'm not sure if that would cause any problems.

Would it be possible to have an automatic "try" when a PR is opened (and perhaps whenever it is updated)?
