### ISSUE TITLE
`delete_merged_branches` doesn’t work with `use_squash_merge`

### ISSUE THREAD

**Issue by EFanZh** [bors-ng/bors-ng#766]
I have

```toml
delete_merged_branches = true
use_squash_merge = true
```

in my `bors.toml` file.

After a PR being merged, the source branch in the same repository still exists.
